//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_FInalAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Information
    {
        public int PlayerIdNum { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public int Contact { get; set; }
        public int EmergencyContact { get; set; }
        public string Description { get; set; }
        public int FloatingXP { get; set; }
        public int GrabBags { get; set; }
        public bool Waver { get; set; }
        public bool CanPlay { get; set; }
    
        public virtual Character_Table Character_Table { get; set; }
    }
}
