//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_FInalAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresteigeClass_RaceList_Table
    {
        public PresteigeClass_RaceList_Table()
        {
            this.Character_Table = new HashSet<Character_Table>();
        }
    
        public int IdList { get; set; }
        public int SkillId { get; set; }
    
        public virtual SkillChart_PrestiegeClass_Race_Table SkillChart_PrestiegeClass_Race_Table { get; set; }
        public virtual ICollection<Character_Table> Character_Table { get; set; }
    }
}
