//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_FInalAssignment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Character_Table> Character_Table { get; set; }
        public virtual DbSet<Player_Information> Player_Information { get; set; }
        public virtual DbSet<PresteigeClass_RaceList_Table> PresteigeClass_RaceList_Table { get; set; }
        public virtual DbSet<SkillChart_Faith_Table> SkillChart_Faith_Table { get; set; }
        public virtual DbSet<SkillChart_General_Table> SkillChart_General_Table { get; set; }
        public virtual DbSet<SkillChart_Magic_Table> SkillChart_Magic_Table { get; set; }
        public virtual DbSet<SkillChart_PrestiegeClass_Race_Table> SkillChart_PrestiegeClass_Race_Table { get; set; }
        public virtual DbSet<SkillChart_Stealth_Table> SkillChart_Stealth_Table { get; set; }
        public virtual DbSet<SkillChart_Weapons_Table> SkillChart_Weapons_Table { get; set; }
        public virtual DbSet<SkillsPurchased_Faith_Table> SkillsPurchased_Faith_Table { get; set; }
        public virtual DbSet<SkillsPurchased_General_Table> SkillsPurchased_General_Table { get; set; }
        public virtual DbSet<SkillsPurchased_Magic_Table> SkillsPurchased_Magic_Table { get; set; }
        public virtual DbSet<SkillsPurchased_Stealth_Table> SkillsPurchased_Stealth_Table { get; set; }
        public virtual DbSet<SkillsPurchased_Weapon_Table> SkillsPurchased_Weapon_Table { get; set; }
    }
}
